### ISSUE TITLE
Update `pipe` to match changes made in #19 for `compose

### ISSUE THREAD

**Issue by Eruant** [littleball-games/lb-f#22]
### Summary of issue

The `pipe` function should work like `compose` but in reverse. See #19  for more details

**Comment by skylize** [comment]
@Eruant Working on this now, but thinking maybe we should just scrap `pipe`.

Is there a scenario in which `pipe` adds an obvious benefit other than reformatting `compose` for people uncomfortable with its right-to-left order of operations? 

Since minimalism is a stated goal for this project, `pipe` strikes me as an unnecessary convenience.

**Comment by Eruant** [comment]
@skylize I get where you are coming from with `pipe`, but now that it's added we should be aware that other code could be using it (even though the chances are rare).

It does raise the question on how best to 'depreciate' old code. We should add a warning code - but this will also require checks on `console` which is more code. I'll keep it on the back burner for now.
